### ISSUE TITLE
Compilation guide

### ISSUE THREAD

**Issue by HerrAugust** [solid-droid/BubbleOS#2]
Hello, I find this project really interesting. However, can you provide some installation guide? Or the support to platformio?

Thanks!

**Comment by solid-droid** [comment]
Right Now whole code is written in Arduino IDE , if interested you can port it to PlatformIO,
I have updated the readme and wiki, please refer the same to install the OS.
[Read Me](https://github.com/solid-droid/BubbleOS/blob/main/README.md)  
[WiKi](https://github.com/solid-droid/BubbleOS/wiki)
